### ISSUE TITLE
/dapp bluejeans fails

### ISSUE THREAD

**Issue by niks3089** [nimbella/command-sets#64]
```
Initialization has failed due to: SyntaxError: Unexpected identifier
    at initializeActionHandler (/nodejsAction/runner.js:57:87)
    at doInit (/nodejsAction/src/service.js:176:16)
    at initCode (/nodejsAction/src/service.js:95:24)
    at /nodejsAction/platform/platform.js:125:17
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
```

**Comment by satyarohith** [comment]
I suspect it's not related to `bluejeans`.
